name: Deploy to Local Machine Window

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Stop existing containers
        run: docker-compose down

      - name: Build Docker image
        run: docker-compose up -d
