name: Docker All-in-One Workflow

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Update local repository
        working-directory: ${{ vars.REPO_PATH }}
        run: |
          git checkout prod
          git pull origin prod
      
      - name: Build and start Docker containers
        working-directory: ${{ vars.DOCKER_PATH }}
        run: |
          echo "checkout path: $(pwd)"
          docker-compose down --volumes --remove-orphans

          # Remove any existing images to force rebuild
          docker-compose rm -f
          
          # Build with no-cache to ensure fresh build
          docker-compose build --no-cache
          
          # Start containers
          docker-compose up -d